Improve
federated-directory/help2 pull request #1
Opened 2022-09-12 18:57 UTC by nemisj

2022-09-12 19:13 UTC, FedWiebe requested changes
1 dingetje..

2022-09-12 19:13 UTC, FedWiebe commented on developer/users-api.md
> +| custom02         |               | 0   | 250 | Custom attribute 2                    |
Alle 3 de custom attributen zijn max 150 characters.

2022-09-13 07:45 UTC, nemisj commented on developer/users-api.md
> +| custom02         |               | 0   | 250 | Custom attribute 2                    |
goed punt! fixed...bijna :D

2022-09-13 07:46 UTC, nemisj commented on developer/users-api.md
> +| custom02         |               | 0   | 250 | Custom attribute 2                    |
ah, het kwam omdat ik de 1 heb vervangen met 2 en dan met 3, toen ik heb de hele regel gekopieerd :D

2022-09-13 07:48 UTC, merged